CREATE DATABASE DBFROULOC
GO

USE DBFROULOC
GO



CREATE TABLE TBL_FUNCIONARIOS (
CODIGO_F INT PRIMARY KEY IDENTITY,
NOME_F NVARCHAR (50) NOT NULL,
DT_NASC_F DATETIME,
SEXO_F CHAR (1) NOT NULL,
ESTADO_CIVIL_F CHAR (1) NOT NULL,
RG_F NVARCHAR (12) NOT NULL,
CPF_F NVARCHAR (14) NOT NULL,
ENDERECO_F NVARCHAR (50) NOT NULL,
CIDADE_F NVARCHAR (50) NOT NULL,
CEP_F NVARCHAR (10) NOT NULL,
ESTADO_F NVARCHAR (50) NOT NULL,
TELEFONE_F NVARCHAR (14) NOT NULL,
CELULAR_F NVARCHAR (15) NOT NULL,
EMAIL_F NVARCHAR (50) NOT NULL,
STATUS_F NVARCHAR (50) NOT NULL
)
GO



CREATE TABLE TBL_CLIENTES (
CODIGO_C INT PRIMARY KEY IDENTITY,
NOME_C VARCHAR (50) NOT NULL,
DT_NASC_C DATETIME,
SEXO_C CHAR (1) NOT NULL,
ESTADO_CIVIL_C CHAR (1) NOT NULL,
RG_C VARCHAR (12) NOT NULL,
CPF_C VARCHAR (14) NOT NULL,
ENDERECO_C VARCHAR (50) NOT NULL,
CIDADE_C VARCHAR (50) NOT NULL,
CEP_C VARCHAR (10) NOT NULL,
ESTADO_C VARCHAR (50) NOT NULL,
TELEFONE_C VARCHAR (15) NOT NULL,
CELULAR_C VARCHAR (15) NOT NULL,
EMAIL_C VARCHAR (50) NOT NULL,
STATUS_C VARCHAR (50) NOT NULL
)
GO

