SELECT * FROM TBL_CLIENTES 

SELECT * FROM TBL_FUNCIONARIOS

CREATE TABLE TBL_ITEM 

(
CODIGO_I INT PRIMARY KEY IDENTITY ,
CODIGO_B INT NOT NULL,
TITULO VARCHAR(100) NOT NULL,
PRECO DECIMAL NOT NULL,
DT_ADQUIRIDA DATETIME NOT NULL,
VALOR_CUSTO DECIMAL NOT NULL,
SITUACAO VARCHAR (100) NOT NULL,
ATORES_P VARCHAR(400) NOT NULL,
DIRETOR VARCHAR (100) NOT NULL,
CAPA_FOTO VARCHAR (MAX)

)

--CREATE TABLE TBL_LOCACAO (




--)


--CREATE TABLE TBL_DEVOLUCAO (

--)

CREATE TABLE TBL_ARTISTA (
CODIGO_A INT PRIMARY KEY IDENTITY,
NOME_A VARCHAR (100) NOT NULL,
DT_NASC DATETIME,
PAIS_NASC VARCHAR (100) NOT NULL,
ARTISTA_FOTO VARCHAR (MAX)
)


CREATE TABLE TBL_GENERO (
CODIGO_G INT PRIMARY KEY IDENTITY,
NOME_G VARCHAR(100) NOT NULL

)


