CREATE TABLE TBL_LOCACAO (
CODIGO_L INT PRIMARY KEY IDENTITY,
CODIGO_F INT NOT NULL,
CPF_C VARCHAR(11) NOT NULL,
NOME_C VARCHAR(100) NOT NULL,
DATA_LOCACAO DATETIME,
DATA_DEVOLUCAO DATETIME,
CODIGO_B INT NOT NULL, 
TITULO VARCHAR(100) NOT NULL,
VALOR_LOCACAO DECIMAL NOT NULL,
VALOR_RECEBIDO DECIMAL NOT NULL,
RECEBIDO CHAR (1) NOT NULL

)

drop table DEVOLUCAO

CREATE TABLE DEVOLUCAO (
CODIGO_D INT PRIMARY KEY IDENTITY,
CODIGO_B INT NOT NULL,
CODIGO_L INT NOT NULL,
DATA_LOCACAO DATETIME,
DATA_DEVOLUCAO DATETIME,
VALOR_LOCACAO DECIMAL NOT NULL,
VALOR_RECEBIDO DECIMAL NOT NULL,
RECEBIDO CHAR (1) NOT NULL,
MULTA DECIMAL NOT NULL,
STATUS_C VARCHAR(100)
)